"""The personal-data inventory (issue #142) covers every path a record can hold.

`docs/personal-data.tsv` classifies each leaf path of the corpus -- whose
data it is and how sensitive -- and `scripts/build_distribution.py` reads
its drop list. Three claims keep it honest: the rules in the script
classify every path the table lists exactly as the table says (the two
cannot drift apart); every path a real parsed record holds is in the table
(a parser that starts emitting a field has to say whose it is); and the
drop list is what the public profile actually removes.
"""

from __future__ import annotations

import importlib.util
import json
import tempfile
import unittest
from pathlib import Path

import local_data
from scraper.cli import _parse_anketa_samples_for_election

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_ROOT = REPO_ROOT / "data"

_spec = importlib.util.spec_from_file_location("pii_inventory", REPO_ROOT / "scripts" / "pii_inventory.py")
pii = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(pii)

TABLE = pii.read_table(REPO_ROOT / pii.TABLE)
TABLE_PATHS = {row.path for row in TABLE}


class TableTests(unittest.TestCase):
    def test_the_table_is_large_and_every_row_is_well_formed(self):
        self.assertGreater(len(TABLE), 1000)
        for row in TABLE:
            with self.subTest(row.path):
                self.assertIn(row.subject, pii.SUBJECTS)
                self.assertIn(row.sensitivity, pii.SENSITIVITIES)
                self.assertIn(row.public, pii.PUBLIC)
                self.assertGreater(row.records, 0)
                self.assertGreater(row.elections, 0)

    def test_the_rules_reproduce_the_table(self):
        # A rule edited without regenerating the table, or a table edited by
        # hand, is a red suite rather than two documents that disagree.
        for row in TABLE:
            with self.subTest(row.path):
                classification = pii.classify(row.path)
                self.assertIsNotNone(classification, "no rule claims a path the table lists")
                self.assertEqual(
                    (classification.subject, classification.sensitivity, classification.public, classification.note),
                    (row.subject, row.sensitivity, row.public, row.note),
                )

    def test_the_drop_list_is_the_tables_drop_rows(self):
        self.assertEqual(sorted(r.path for r in TABLE if r.public == "drop"), sorted(pii.PUBLIC_PROFILE_DROPS))
        self.assertEqual(sorted(r.path for r in TABLE if r.public == "conditional"), sorted(pii.PUBLIC_PROFILE_CONDITIONAL))
        for path in pii.PUBLIC_PROFILE_DROPS + pii.PUBLIC_PROFILE_CONDITIONAL:
            with self.subTest(path):
                row = next(r for r in TABLE if r.path == path)
                self.assertEqual((row.subject, row.sensitivity), ("third-party", "contact"))

    def test_the_document_is_generated_from_the_table(self):
        document = (REPO_ROOT / pii.DOCUMENT).read_text(encoding="utf-8")
        self.assertIn("Generated by `scripts/pii_inventory.py`", document)
        for path in pii.PUBLIC_PROFILE_DROPS:
            self.assertIn(f"`{path}`", document)
        # The headline third-party facts the inventory exists to state.
        for path in (
            "normalized.anketa.vaiku-vardai-pavardes",
            "normalized.anketa.sutuoktinio-vardas-pavarde",
            "normalized.politines-kampanijos-dalyvio-duomenys[].izdininkas.vardas-pavarde",
        ):
            self.assertIn(f"`{path}`", document)


class LeafPathTests(unittest.TestCase):
    def test_list_indices_collapse_and_empty_containers_are_leaves(self):
        record = {
            "candidateId": "x",
            "normalized": {"anketa": {"uzsienio-kalbos": ["a", "b"], "seimos-nariai": [{"vardas": "A"}, {"vardas": "B"}], "kita": {}}, "biografija": None},
            "rawData": {"profile": {"fields": []}},
        }
        self.assertEqual(
            pii.leaf_paths(record),
            {
                "candidateId",
                "normalized.anketa.uzsienio-kalbos[]",
                "normalized.anketa.seimos-nariai[].vardas",
                "normalized.anketa.kita",
                "normalized.biografija",
                "rawData.profile.fields[]",
            },
        )


class RealRecordTests(unittest.TestCase):
    """Records a parser actually produced, from fixtures: every leaf path is
    in the table."""

    @classmethod
    def setUpClass(cls):
        cls._tmp = tempfile.TemporaryDirectory()
        cls.paths: set[str] = set()
        for election in ("2019-prezidento", "2016-seimo"):
            fixtures = REPO_ROOT / "samples" / "html" / election
            local_data.require(fixtures)
            output = Path(cls._tmp.name) / election
            _parse_anketa_samples_for_election(
                election_id=election, candidate_ids=None, samples_root=fixtures, output_root=output
            )
            for path in output.glob("*.json"):
                cls.paths |= pii.leaf_paths(json.loads(path.read_text(encoding="utf-8")))

    @classmethod
    def tearDownClass(cls):
        cls._tmp.cleanup()

    def test_every_path_a_parsed_record_holds_is_classified(self):
        self.assertTrue(self.paths)
        self.assertEqual(sorted(self.paths - TABLE_PATHS), [], "a parser emits a path the inventory does not classify")


class CorpusTests(unittest.TestCase):
    def test_a_sample_of_every_election_holds_no_unclassified_path(self):
        # The full pass takes minutes; 40 records per election reach every
        # section shape of every era in a few seconds.
        local_data.require_corpus()
        election_ids = pii.corpus_elections(DATA_ROOT)
        counts = pii.measure(DATA_ROOT, election_ids, sample=40)
        unknown = sorted(c.path for c in counts if c.path not in TABLE_PATHS)
        self.assertEqual(unknown, [], "run scripts/pii_inventory.py to classify and regenerate")


if __name__ == "__main__":
    unittest.main()
